services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-pg_user_name}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pg_password}
      PGDATA: ${POSTGRES_DATA:-/var/lib/postgresql/data/pgdata}
    volumes:
      - ${POSTGRES_HOST_DATA:-./postgres}:${POSTGRES_DATA:-/var/lib/postgresql/data/pgdata}
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: unless-stopped

volumes:
  postgres:

